apiVersion: v1
kind: Service
metadata:
  name: pc-price-tracker
  namespace: pc-price-tracker
  labels:
    app.kubernetes.io/name: pc-price-tracker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pc-price-tracker
  ports:
    - name: http
      port: 80
      targetPort: http
